title: "My Blog"
author: "Rodolfo III Salazar"
description: "My blog"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: true
show_frame: true
show_sidebar: false
show_minimal: false

# Menu
navigation:
  - {file: "home.html", title: "Home", sidebaricon: "home"}
  - {file: "archive.html", title: "Writings", sidebaricon: "pen"}
  - {file: "code.html", title: "Code", sidebaricon: "code"}
  - {file: "contact.html", title: "Contact", sidebaricon: "envelope"}

external:
  - {title: Github, icon: github, url: "https://github.com/rodsalazar324-commits"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/rodolfobsalazar/"}

plugins:
  - jekyll-feed
