title: "My Blog"
author: "Rodolfo III Salazar"
description: "My blog"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
- {file: "home.html", title: "Home", sidebaricon: "home"}
- {file: "archive.html", title: "Writings", sidebaricon: "pen"}
- {file: "code.html", title: "Code", sidebaricon: "code"}
- {file: "contact.html", title: "Contact", sidebaricon: "envelope"}


external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Github, icon: github, url: "https://github.com/rodsalazar324-commits"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/rodolfobsalazar/"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
 
